# Generated by Django 4.1.3 on 2023-01-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomClient', models.CharField(max_length=20)),
                ('Adress', models.CharField(max_length=50)),
                ('Telephone', models.CharField(max_length=13)),
                ('Email', models.EmailField(max_length=100)),
                ('MotPass', models.CharField(max_length=32)),
                ('CodeConfirmation', models.IntegerField()),
            ],
        ),
    ]
