# Generated by Django 4.1.3 on 2023-01-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomMateriel', models.CharField(max_length=30)),
                ('QnteTotal', models.IntegerField()),
                ('QnteDisponible', models.IntegerField()),
                ('QnteLouer', models.IntegerField()),
            ],
        ),
    ]
