# Generated by Django 4.1.3 on 2023-01-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecole', '0002_materiel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeCommande', models.IntegerField()),
                ('MontantTotal', models.FloatField()),
                ('DateCommande', models.DateField()),
                ('EtatCommande', models.CharField(max_length=10)),
            ],
        ),
    ]
