# Generated by Django 4.1.3 on 2023-01-06 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecole', '0003_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeCommande', models.IntegerField()),
                ('MontantTotal', models.FloatField()),
                ('DateCommande', models.DateField()),
                ('EtatCommande', models.CharField(max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ecole.client')),
            ],
        ),
    ]
