# Generated by Django 4.1.3 on 2023-01-06 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecole', '0004_commandeclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QnteDemande', models.IntegerField()),
                ('PrixUnit', models.IntegerField()),
                ('NbreJour', models.IntegerField()),
                ('DateDebut', models.DateField()),
                ('commandeclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ecole.commandeclient')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ecole.materiel')),
            ],
        ),
    ]
