# Generated by Django 4.1.3 on 2023-01-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecole', '0006_commande_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('montant', models.FloatField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('etat', models.CharField(default='aucun', max_length=25)),
            ],
        ),
    ]
