# Generated by Django 4.1.3 on 2023-01-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecole', '0007_codeclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeclient',
            name='code',
            field=models.IntegerField(),
        ),
    ]
