# Generated by Django 4.1.3 on 2023-01-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecole', '0008_alter_codeclient_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailcommande',
            name='Montant',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='client',
            table='app_ecole_client',
        ),
    ]
